# Dictation Builder Configuration
# Example configuration file for command-line usage

# Audio processing parameters
tempo: 0.92                    # Playback speed (0.5-2.0, where 1.0 is normal speed)
repeats: 3                     # Number of times to repeat each sentence
pause_ms: 10000               # Pause between sentence repeats (milliseconds)
inter_sentence_pause_ms: 10000 # Pause between different sentences (milliseconds)
pad_ms: 100                   # Padding added to sentence boundaries (milliseconds)
fade_ms: 8                    # Fade in/out duration to prevent clicks (milliseconds)
sample_rate: 44100            # Audio sample rate (Hz)

# Alignment parameters
alignment:
  window_tokens: 4000         # Search window size in tokens
  elastic_gap: 10             # Allowed gap between expected and actual span
  min_accept: 0.82            # Minimum score for automatic acceptance
  warn_accept: 0.75           # Warning threshold score
  token_ratio_cutoff: 92      # Fuzzy matching similarity threshold (0-100)
  coverage_min: 0.80          # Minimum token coverage required
  small_sentence_coverage_min: 0.67  # Coverage for sentences < 6 tokens

  # Scoring weights
  weights:
    token_sim: 0.50           # Token similarity weight
    coverage: 0.25            # Coverage weight
    gap_penalty: 0.20         # Gap penalty weight
    anchor_bonus: 0.08        # Anchor bonus weight
    bigram_bonus: 0.05        # Bigram bonus weight

# Fallback parameters (used when initial alignment fails)
fallback:
  expand_window_tokens: 1000  # Additional tokens to search
  elastic_gap: 18             # Relaxed gap allowance
  token_ratio_cutoff: 88      # Relaxed similarity threshold

